exports.privKey = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQggdXdwlUM8lnFqaoa
kQyj25j0XWp0bBorWljDwbxP4dahRANCAAQRENPb2MPYOyTbofp/btCZh4ztHRey
Z/FduCzx6aqr7C2PaBpA7vMqSQay65j8rWzb/tMoLmrYnuQXRcQ7J6m/
-----END PRIVATE KEY-----
`

exports.pubKey = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEERDT29jD2Dsk26H6f27QmYeM7R0X
smfxXbgs8emqq+wtj2gaQO7zKkkGsuuY/K1s2/7TKC5q2J7kF0XEOyepvw==
-----END PUBLIC KEY-----
`
